management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

spring:
  jpa:
    show-sql: true

#  detailed transaction management logs
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG

app:
  user:
    password: password
    email: email@email.com